### ISSUE TITLE
Can't open live TV or TV guide

### ISSUE THREAD

**Issue by tomzazo** [markop159/plugin.video.a1tvgo#2]
There's an issue with opening live TV or TV guide in the addon. The responses from the API requests with information regarding to channels can't be parsed into the current logic and Kodi is logging the following error:

>2022-11-27 12:20:17.432 T:4520    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.a1tvgo\default.py", line 473, in <module>
                                                       indexLiveTV()
                                                     File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.a1tvgo\default.py", line 145, in indexLiveTV
                                                       for channel in res['data']['channelList']['channels']['edges']:
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--

I've prepared a pull request with a fix: #1 

I've also updated the `liveTV` GraphQL query in the same PR. The `channelList` query could also be updated in the future.

Please check.

**Comment by markop159** [comment]
Thank you for updated files.
I additionally updated DRM license URL in default.py
